name: GitHub Events Automation

on:
  # Triggers the workflow on a new pull request
  pull_request:
    branches:
      - main
  
  # Triggers the workflow when a pull request is merged into the main branch
  push:
    branches:
      - main

  # Triggers when a new collaborator (contributor) is added
  member:
    types: [added]

jobs:
  # Job 1: Notify team on pull request creation
  notify-on-pull-request:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Notify the team about the new pull request
        run: echo "New pull request opened. Review it soon!"

  # Job 2: Notify team on successful merge into main branch
  notify-on-merge:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Notify the team about the successful merge
        run: echo "Pull request merged to main branch. Notify team for deployment."

  # Job 3: Welcome a new contributor
  welcome-new-contributor:
    if: github.event_name == 'member'
    runs-on: ubuntu-latest
    steps:
      - name: Welcome new contributor
        run: echo "Welcome, ${{ github.event.member.login }}! 🎉 Thank you for joining the project!"
